### ISSUE TITLE
Arreglar algunos estilos en la sección de nodeco

### ISSUE THREAD

**Issue by silvermiguel96** [node-co/node-co#3]

**Comment by camilomontoyau** [comment]
@silvermiguel96 podrías por favor ser más preciso y agregar capturas de pantalla?

**Comment by silvermiguel96** [comment]
@calypsobronte me ayudas con eso, ya que yo monte los Issues con la información que dejaste en el canal.

**Comment by jnosornov** [comment]
El issue se cerro por falta de actividad
