### ISSUE TITLE
Encuadre en los slides de organizadores

### ISSUE THREAD

**Issue by silvermiguel96** [node-co/node-co#4]

**Comment by camilomontoyau** [comment]
@silvermiguel96 podrías por favor agregar capturas de pantalla de bug?

**Comment by silvermiguel96** [comment]
@calypsobronte me ayudas con eso, ya que yo monte los Issues con la información que dejaste en el canal.

**Comment by jnosornov** [comment]
El issue se cerro por falta de actividad
