### ISSUE TITLE
 Arreglar varios detalles en los estilos como font tamaños entre otros.

### ISSUE THREAD

**Issue by silvermiguel96** [node-co/node-co#6]

**Comment by camilomontoyau** [comment]
@silvermiguel96 podrías dar más detalle y agregar capturas de pantalla por favor?

**Comment by silvermiguel96** [comment]
@calypsobronte me ayudas con eso, ya que yo monte los Issues con la información que dejaste en el canal.

**Comment by jnosornov** [comment]
El issue se cerro por falta de actividad
